#!/bin/bash

echo "Installing fix_libs.sh"
if [ -f $HOME/.local/share/Steam/steamapps/common/OneShot/fix_libs.sh ]; then
	echo "Already installed"
else
	cp fix_libs.sh $HOME/.local/share/Steam/steamapps/common/OneShot/
	chmod +x $HOME/.local/share/Steam/steamapps/common/OneShot/fix_libs.sh
fi

echo "Installing journal.sh"
if [ -f $HOME/.local/share/Steam/steamapps/common/OneShot/journal.sh ]; then
	echo "Already installed"
else
	cp journal.sh $HOME/.local/share/Steam/steamapps/common/OneShot/
	chmod +x $HOME/.local/share/Steam/steamapps/common/OneShot/journal.sh
fi

echo "Installing onejournal"
chmod +x onejournal
if [ -f /usr/bin/onejournal ]; then
	echo "Already installed"
else
	sudo cp onejournal /usr/bin/
	sudo chmod +x /usr/bin/onejournal
fi

echo "Fixing libraries"
./~/.local/share/Steam/steamapps/common/OneShot/fix_libs.sh
